#! /bin/bash

aplay_pid=$(pidof aplay)

# Use the --length_scale argument to adjust speed (Smaller is faster).
# Setting --noise_scale and --noise_w to 0 appears to help improve
# enunciation at higher speeds.

if [ -z "$aplay_pid"]
then
    xclip -out -selection primary | xclip -in -selection clipboard
    xsel --clipboard | tr "\n" " " \
        | piper --model ~/piper/en_US-lessac-medium.onnx --length_scale 0.1 --noise_w 0 --noise_scale 0 \
        | aplay -r 22050 -f S16_LE -t raw -
else 
    kill $aplay_pid
fi
